# Generated by Django 4.2.5 on 2024-05-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_cliente_vendedor_livro_categoria_livro_origem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
